### ISSUE TITLE
게임 아키텍처 초안구성

### ISSUE THREAD

**Issue by Submittt** [Submittt/BlackJackProject#1]

**Comment by dowon0418** [comment]
![Uploading 제목 없음.png…]()

**Comment by dowon0418** [comment]
![블랙잭 게임 순서도](https://github.com/user-attachments/assets/4acab7cd-de11-4c4c-b4ea-cf513e4526a7)

**Comment by Submittt** [comment]
![Image](https://github.com/user-attachments/assets/b80f4c2a-e004-42c4-9f7b-50c4cbfbcb26)

**Comment by dowon0418** [comment]
![블랙잭 게임 순서도](https://github.com/user-attachments/assets/f4928372-9533-4a01-9f65-e6bc6cac4aae)
